name: marlin_auto_build

on:
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'
  workflow_dispatch:

jobs:
  create_builds:
    runs-on: ubuntu-latest
    steps:
    - uses: bwvolleyball/marlin_auto_build@master